require('ggplot2')
require('hexbin')
args <- commandArgs(TRUE)
input <- as.character(args[1])
output <- as.character(args[2])
data = read.table(input)
pdf(output)
print(ggplot(data,aes(x=data$V3))+geom_histogram()+xlab("5' overlap count"))
print(ggplot(data,aes(x=data$V4))+geom_histogram()+xlab("3' overlap count"))
print(ggplot(data,aes(x=data$V3,y=data$V4))+stat_binhex(bins=200)+xlab("5' overlap count")+ylab("3' overlap count"))
dev.off()
